services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
        depends_on:
            - backend
        environment:
            - NEXT_PUBLIC_API_URL=http://localhost:8000

    backend:
        build: ./backend
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app
        depends_on:
            - db
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
            - MAIL_SERVER=mailhog
            - MAIL_PORT=1025

    db:
        image: postgres:13
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydatabase
        volumes:
            - postgres_data:/var/lib/postgresql/data

    mailhog:
        image: mailhog/mailhog
        platform: linux/amd64
        ports:
            - "1025:1025"
            - "8025:8025"

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: password
        ports:
            - "5050:80"
        depends_on:
            - db

volumes:
    postgres_data:
